#cloud-config
package_upgrade: true

packages:
 - epel-release
 - git
 - python-devel
 - python-tox
 - python-virtualenv
 - rpmdevtools
 - rpmlint
 - rpm-build
 - docker-io
 - libffi-devel
 - "@buildsys-build"
 - openssl-devel
 - wget
 - curl
 - enchant
 - python-pip
 - ruby-devel

runcmd:
 - yum up
 - pip install buildbot-slave
 - gem install fpm
 - systemctl enable docker
 - systemctl start docker
 - docker pull busybox
 - docker pull openshift/busybox-http-app
 - docker pull python:2.7-slim
 - mkdir ~root/.pip
 - |
   cat > ~root/.pip/pip.conf <<EOF
   [global]
   find-links = file:///var/cache/wheelhouse
   EOF
