#!/bin/sh

# A script is needed to do this because of http://www.openradar.me/18945659.
# See Note2 in
# http://trac.buildbot.net/wiki/UsingLaunchd#Samplepropertylistforaslave
# for more details.

PATH=$HOME/Library/python/2.7/bin:$PATH

eval $(ssh-agent -s)
ssh-add

exec twistd --nodaemon -y ./buildbot.tac
