#!/usr/bin/env python

import sys
from common import get_driver, load_manifest


def get_images(driver, name):
    return [
        image for
        image in driver.list_images(ex_owner="self")
        if image.extra['tags'].get('base-name') == image_name
    ]


def tag_latest_image(driver, name, tags):
    images = get_images(driver, name)

    def timestamp(image):
        return image.extra.get('timestamp')
    latest_image = max(images, key=timestamp)

    driver.ex_create_tags(latest_image, tags=tags)

DISTRO = sys.argv[1]
base, manifest = load_manifest(DISTRO)

for image in manifest['images']:
    image_name = image['name']

    provider_slug = image.pop('provider', 'ec2')
    region_slug = image.pop('region', None)
    driver = get_driver(provider_slug, region_slug)

    tag_latest_image(image_name, tags={'production': 'true'})
