#!/usr/bin/env python

from common import aws_config, driver, wait_for_image


def get_image(name):
    try:
        return [s for s in driver.list_images(ex_owner="self") if s.name == name][0]
    except IndexError:
        raise ValueError("Unknown EC2 image.", name)

def copy_image(source, destination):
    image = driver.copy_image(
            region=aws_config['region'],
            image=get_image(source),
            name=destination)

    print "%s: %s" % (destination, image.id)
    wait_for_image(image)
    return image.id


copy_image('staging-buildslave-fedora-20', 'buildslave-fedora-20')
copy_image('staging-buildslave-fedora-20-zfs-test', 'buildslave-fedora-20-zfs-test')
